



export const TYPES = {
    // CONTADOR
    INCREMENTAR: "INCREMENTAR",
    DECREMENTAR: "DECREMENTAR",
    RESETEAR: "RESETEAR",
    // VISIBILIDAD
    MOSTRAR: "MOSTRAR",
    OCULTAR: "OCULTAR",
    // CARRITO DE COMPRAS
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_ONE_ITEM: "REMOVE_ONE_ITEM",
    REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS",
    CLEAR_CART: "CLEAR_CART"
}