import Navigation from '@/components/Clase_2/Navigation'
import Head from 'next/head'

const Contacto = () => {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Navigation />
    </main>
  </>
  )
}

export default Contacto