

import Head from "next/head";
import BBApp from "@/components/bbapp/BBApp";
import ShoppingCart from "@/components/shoppingCart/ShoppingCart";
import CrudApp from "@/components/santosApp/CrudApp";
import Icon from "@/components/Icon";

export default function Home({articles}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      </header>
      <main>
        <Icon />
      </main>
    </>
  );
}
