import Head from 'next/head'
import Navigation from '@/components/Navigation'

const Services = () => {
  return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
                <Navigation />
        </header>
        <main> 
            <h1>Services</h1>
            <section className='container'>
              <h1>Home</h1>
              <p>Lorem ipsum dolor sit amet.</p>
            </section>
        </main>


        {/******* PAGE STYLES ******/}
        <style jsx>{`
          h1 {
            color: orange;
          }
          p {
            color: yellow;
          }
          .container {
            background-color: blue;
          }
        `}</style>
    </>
  )
}

export default Services