import Head from "next/head";
import Navigation from "@/components/Clase_2/Navigation";
import RelojEffect from "@/components/Clase_4/RelojEffect";
import Books from "@/components/Clase_3/Books";
import BooksContextProvider from "@/context/BooksContextProvider";
import Header from "@/components/Clase_5/Header";
import ThemeContextProvider from "@/context/ThemeContextProvider";
import Section from "@/components/Clase_5/Section";
import Footer from "@/components/Clase_5/Footer";
import Contador from "@/components/Clase_3/Contador";
import ShoppingCart from "@/components/Clase_6/ShoppingCart";
import BBApp from "@/components/Clase_7/BBApp";
import CrudApp from "@/components/Clase_8/CrudApp";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <Navigation />
        </header>
        <CrudApp />
      </main>
    </>
  );
}
