import Head from 'next/head'
import Navigation from '@/components/Clase_2/Navigation'

const Services = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <Navigation />
        </header>
        <h1>Services</h1>
      </main>
    </>
  );
};

export default Services;
